// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sdk "github.com/conduitio/conduit-connector-sdk"
)

// Writer is an autogenerated mock type for the Writer type
type Writer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Writer) Close() {
	_m.Called()
}

// Write provides a mock function with given fields: ctx, records
func (_m *Writer) Write(ctx context.Context, records []sdk.Record) error {
	ret := _m.Called(ctx, records)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []sdk.Record) error); ok {
		r0 = rf(ctx, records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
