// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	"github.com/conduitio/conduit-commons/opencdc"
	mock "github.com/stretchr/testify/mock"
)

// ZendeskCursor is an autogenerated mock type for the ZendeskCursor type
type ZendeskCursor struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *ZendeskCursor) Close() {
	_m.Called()
}

// FetchRecords provides a mock function with given fields: ctx
func (_m *ZendeskCursor) FetchRecords(ctx context.Context) ([]opencdc.Record, error) {
	ret := _m.Called(ctx)

	var r0 []opencdc.Record
	if rf, ok := ret.Get(0).(func(context.Context) []opencdc.Record); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]opencdc.Record)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
